### ISSUE TITLE
New PyPI release

### ISSUE THREAD

**Issue by narpfel** [underchemist/nanonispy#1]
Commit fc91606bcc70b78c40da4f94bee595b6ca958233 is not included in the latest PyPI release, so using `Spec` is rather annoying because [this line](https://github.com/underchemist/nanonispy/commit/fc91606bcc70b78c40da4f94bee595b6ca958233#diff-5466f5db53e8ec2c7e5379208c9d5042R370) is missing.

Could you please push a new release to the PyPI? Thanks in advance!

**Comment by underchemist** [comment]
Hi Narpfel,

it's been awhile since I looked at everything and had to relearn how to upload to pypi but there should be an updated version that is tied to the latest commit. 

thanks for asking for help though!

Sebastien

**Comment by narpfel** [comment]
Thanks a lot! :+1:
