### ISSUE TITLE
error: package directory 'nanonispy\tests' does not exist

### ISSUE THREAD

**Issue by jhellerstedt** [underchemist/nanonispy#11]
Hi,

I've got a guy trying to install nanonispy from a git clone/ running install, and it throws the following error:

```bash
$python setup.py install
running install
running bdist_egg
running egg_info
creating nanonispy.egg-info
writing nanonispy.egg-info\PKG-INFO
writing dependency_links to nanonispy.egg-info\dependency_links.txt
writing requirements to nanonispy.egg-info\requires.txt
writing top-level names to nanonispy.egg-info\top_level.txt
writing manifest file 'nanonispy.egg-info\SOURCES.txt'
error: package directory 'nanonispy\tests' does not exist
```

I've been scratching my head looking at the `setup.py` file but can't offer you any further insight into why its hanging.

Cheers,

Jack

**Comment by underchemist** [comment]
Hi Jack,

This should be fixed in d8fdcd23cdac698caf2139d2a0c066d591eb553b. Thanks for your patience.

Cheers,

Sebastien
