### ISSUE TITLE
Swapping of nx, ny parameters when reading binary data

### ISSUE THREAD

**Issue by underchemist** [underchemist/nanonispy#12]
from david.wander at web dot de

> Dear Yann-Sebastien,
> 
> first of all, I would like to thank you for sharing your nanonispy library.
> It makes the data treatment of my measurements much easier!
> 
> However, I just found a major bug in the _load_data function of the Grid class.
> Line 230 of read.py (nanonispy Version 1.0.7) reads:
> 
> griddata_shaped = griddata.reshape((nx, ny, exp_size_per_pix))
> 
> Here you are confusing x and y. The correct code would be:
> 
> griddata_shaped = griddata.reshape((ny, nx, exp_size_per_pix))
> 
> Of course this then implies that after loading the data, you first have to address y and then x, so for example like this:
> 
> grid.signals['params'][index_y][index_x][param_index]
> 
> 
> I admit that it is easy to miss this error because it seems to give the right array shapes but if you take a close look, you will realize that when going from
> signals['params'][0][0] to signals['params'][1][0] (i.e. increasing the x index by 1), it is actually the y coordinate that changes (signals['params'][1][0][3])
> For square shaped grids, this might not be a desaster, as it only leads to a grid rotated by 90° but as soon as you work with other shapes, things get totally messy.
> 
> 
> I hope you will correct this in the next version of the package!
> 
> 
> Best regards,
> 
> David Wander

**Comment by underchemist** [comment]
@david when you see this could you install from issue12_swappedxy branch and see if this fixes your issues? I don't have non-square data to do my own testing with so I'm relying on you!

**Comment by jhellerstedt** [comment]
I worked on this problem forever ago:
https://github.com/underchemist/nanonispy/pull/4

Happy to send you some rectangular sxm files; but basically I think David nailed it, you just change the nx, ny convention on the raw bitstream read, and everything starts working again

**Comment by djwander** [comment]
Yes, indeed, that fixes the problem!

**Comment by underchemist** [comment]
@jhellerstedt thanks, I remember now from a long time ago, I never got around to it :P

Fixed as described above in 1.0.8

https://pypi.org/project/nanonispy/1.0.8/
https://github.com/underchemist/nanonispy/releases/tag/1.0.8
