### ISSUE TITLE
Incompatible with numpy

### ISSUE THREAD

**Issue by ceds92** [underchemist/nanonispy#23]
np.int, np.float, etc have been deprecated in newer versions of numpy. There is an open pull request to rectify this

**Comment by ceds92** [comment]
https://github.com/underchemist/nanonispy/pull/22

**Comment by cahlikales** [comment]
would be great if it could be accepted

**Comment by ceds92** [comment]
Uploaded nanonispy2 to pypi:

pip install nanonispy2
